ignore = []

max_width = 100
tab_spaces = 4
hard_tabs = false

format_strings = true
binop_separator = "Back"
blank_lines_lower_bound = 1
brace_style = "PreferSameLine"
use_field_init_shorthand = true

wrap_comments = true
format_code_in_doc_comments = true

imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"